model_name: "common-policy-4400-nocamera_jit.pt"
framework: "isaacgym"
rows: 4
cols: 3
decimation: 4
num_observations: 53
observations: [ "commands", "ang_vel", "gravity_vec",  "dof_pos", "dof_vel", "actions" ]
observations_history:  [0,1,2,3,4,5,6,7,8,9]
clip_obs: 100.0
clip_actions_lower: [ -100, -100, -100,
                      -100, -100, -100,
                      -100, -100, -100,
                      -100, -100, -100 ]
clip_actions_upper: [ 100, 100, 100,
                      100, 100, 100,
                      100, 100, 100,
                      100, 100, 100 ]
rl_kp: [ 20, 20, 20,
         20, 20, 20,
         20, 20, 20,
         20, 20, 20 ]
rl_kd: [ 0.5, 0.5, 0.5,
         0.5, 0.5, 0.5,
         0.5, 0.5, 0.5,
         0.5, 0.5, 0.5 ]
hip_scale_reduction: 1.0
hip_scale_reduction_indices: [ 0, 3, 6, 9 ]
num_of_dofs: 12
action_scale: 0.25

lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05

commands_scale: [ 2.0, 2.0, 0.25 ]

torque_limits: [ 33.5, 33.5, 33.5,
                 33.5, 33.5, 33.5,
                 33.5, 33.5, 33.5,
                 33.5, 33.5, 33.5 ]

# 添加相机配置段
use_camera: true
depth_width: 80
depth_height: 80
max_depth: 2.0
depth_feature_dim: 6400  # 若使用CNN提取特征，需改为实际输出维度
use_depth_cnn: false  # 若使用预训练CNN设为true
depth_cnn_model: "depth_encoder.pt"  # 特征提取模型文件名